EXPORT struct cdf_prim_loc {
	unsigned int __count;
	wchar_t **__names;
	struct cell_func *cdf_q_signal;
	struct cell_func *cdf_q_dr;
	struct cell_array *cdf_spn;
	struct cell_func_box *cdf_squeeze;
	struct cell_func_box *cdf_is_simple;
	struct cell_func_box *cdf_is_numeric;
	struct cell_func_box *cdf_is_char;
	struct cell_func_box *cdf_is_integer;
	struct cell_func_box *cdf_is_bool;
	struct cell_func_box *cdf_is_span;
	struct cell_func_box *cdf_max_shp;
	struct cell_func_box *cdf_has_nat_vals;
	struct cell_func_box *cdf_chk_scl;
	struct cell_func_box *cdf_chk_valid_shape;
	struct cell_func_box *cdf_both_simple;
	struct cell_func_box *cdf_both_numeric;
	struct cell_func_box *cdf_both_integer;
	struct cell_func_box *cdf_both_char;
	struct cell_func_box *cdf_both_bool;
	struct cell_func_box *cdf_any;
	struct cell_moper *cdf_numeric;
	struct cell_doper *cdf_ambiv;
	struct cell_func_box *cdf_same;
	struct cell_moper_box *cdf_veach;
	struct cell_moper *cdf_scalar;
	struct cell_func *cdf_idx_shp_check;
	struct cell_func *cdf_idx_rng_check;
	struct cell_func *cdf_set;
	struct cell_func *cdf_brk;
	struct cell_func *cdf_rgt;
	struct cell_func *cdf_lft;
	struct cell_func *cdf_reshape;
	struct cell_func *cdf_rho;
	struct cell_func *cdf_cat;
	struct cell_func *cdf_depth;
	struct cell_func *cdf_eqv;
	struct cell_func *cdf_nqv;
	struct cell_func_box *cdf_sqd_vec;
	struct cell_func *cdf_sqd;
	struct cell_func *cdf_index_gen;
	struct cell_func *cdf_index_of;
	struct cell_func *cdf_iot;
	struct cell_func *cdf_dis;
	struct cell_func *cdf_enclose;
	struct cell_func *cdf_par;
	struct cell_func *cdf_conjugate;
	struct cell_func *cdf_add;
	struct cell_func *cdf_sub;
	struct cell_func *cdf_sign;
	struct cell_func *cdf_mul;
	struct cell_func *cdf_div;
	struct cell_func *cdf_absolute;
	struct cell_func *cdf_residue;
	struct cell_func *cdf_res;
	struct cell_func *cdf_floor_array;
	struct cell_func *cdf_min;
	struct cell_func *cdf_ceil_array;
	struct cell_func *cdf_max;
	struct cell_func *cdf_exp;
	struct cell_func *cdf_log;
	struct cell_func *cdf_pitimes;
	struct cell_func *cdf_trig;
	struct cell_func *cdf_cir;
	struct cell_func *cdf_binomial;
	struct cell_func *cdf_fac;
	struct cell_func *cdf_notscl;
	struct cell_func *cdf_without;
	struct cell_func *cdf_not;
	struct cell_func *cdf_logand;
	struct cell_func *cdf_and;
	struct cell_func *cdf_logor;
	struct cell_func *cdf_lor;
	struct cell_func *cdf_nan;
	struct cell_func *cdf_nor;
	struct cell_func *cdf_lessthan;
	struct cell_func *cdf_lth;
	struct cell_func *cdf_lesseql;
	struct cell_func *cdf_lte;
	struct cell_func_box *cdf_eql_vec;
	struct cell_func *cdf_equal;
	struct cell_func *cdf_eql;
	struct cell_func *cdf_greatereql;
	struct cell_func *cdf_gte;
	struct cell_func *cdf_greaterthan;
	struct cell_func *cdf_gth;
	struct cell_func *cdf_firstocc;
	struct cell_func_box *cdf_neq_vec;
	struct cell_func *cdf_noteq;
	struct cell_func *cdf_neq;
	struct cell_func *cdf_mix;
	struct cell_func *cdf_take;
	struct cell_func *cdf_tke;
	struct cell_func *cdf_split;
	struct cell_func *cdf_drop;
	struct cell_func *cdf_drp;
	struct cell_func *cdf_reverse_last;
	struct cell_func *cdf_rotate_last;
	struct cell_func *cdf_rot;
	struct cell_moper *cdf_com;
	struct cell_moper *cdf_map;
	struct cell_moper_box *cdf_reduce;
	struct cell_moper_box *cdf_nwreduce;
	struct cell_moper *cdf_rdf;
	struct cell_func *cdf_rpf;
	struct cell_moper *cdf_scf;
	struct cell_doper *cdf_dot;
	struct cell_moper *cdf_oup;
	struct cell_doper *cdf_pow;
	struct cell_doper *cdf_jot;
} cdf_prim;

EXPORT int cdf_q_signal(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_q_dr(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_spn(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_squeeze(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_is_simple(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_is_numeric(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_is_char(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_is_integer(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_is_bool(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_is_span(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_max_shp(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_has_nat_vals(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_chk_scl(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_chk_valid_shape(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_both_simple(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_both_numeric(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_both_integer(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_both_char(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_both_bool(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_any(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_numeric(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_ambiv(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_same(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_veach(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_scalar(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_idx_shp_check(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_idx_rng_check(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_set(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_brk(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_rgt(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_lft(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_reshape(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_rho(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_cat(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_depth(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_eqv(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_nqv(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_sqd_vec(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_sqd(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_index_gen(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_index_of(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_iot(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_dis(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_enclose(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_par(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_conjugate(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_add(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_sub(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_sign(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_mul(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_div(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_absolute(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_residue(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_res(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_floor_array(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_min(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_ceil_array(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_max(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_exp(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_log(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_pitimes(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_trig(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_cir(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_binomial(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_fac(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_notscl(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_without(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_not(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_logand(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_and(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_logor(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_lor(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_nan(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_nor(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_lessthan(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_lth(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_lesseql(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_lte(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_eql_vec(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_equal(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_eql(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_greatereql(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_gte(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_greaterthan(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_gth(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_firstocc(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_neq_vec(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_noteq(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_neq(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_mix(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_take(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_tke(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_split(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_drop(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_drp(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_reverse_last(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_rotate_last(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_rot(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_com(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_map(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_reduce(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_nwreduce(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_rdf(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_rpf(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_scf(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_dot(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_oup(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_pow(struct cell_array **, struct cell_array *, struct cell_array *);
EXPORT int cdf_jot(struct cell_array **, struct cell_array *, struct cell_array *);
