$pdf = $Args[0] + ".pdf"
$xml = $Args[0] + ".xml"
echo "Building $xml to $pdf..."
fop -c fop.xconf -xsl fo.xsl -xml $xml -pdf $pdf
start $pdf
# SIG # Begin signature block
# MIIEMwYJKoZIhvcNAQcCoIIEJDCCBCACAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU5QTuebG2LEUGvy9a3Va+APeU
# Xg6gggI9MIICOTCCAaagAwIBAgIQftjm+laDwL5JEV3iBpuJbjAJBgUrDgMCHQUA
# MCwxKjAoBgNVBAMTIVBvd2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdDAe
# Fw0xMzA4MjcyMDA0MjFaFw0zOTEyMzEyMzU5NTlaMBoxGDAWBgNVBAMTD1Bvd2Vy
# U2hlbGwgVXNlcjCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAqyHUXl+xlZ8m
# yZsqmazKWU784kKcBvazsSA7Z/HdMw8KUp3oeX6p+VE5O0rbnsClSAAgz/k+HWfm
# rVXb4I99Y3rDaA/ftThlrq+lt0N/kRqQOn6INm8aWxJRnBlVkAej4C+DND5dyl94
# R4NpgdQJm6F1D51ZFWBFMr/6rkCvP40CAwEAAaN2MHQwEwYDVR0lBAwwCgYIKwYB
# BQUHAwMwXQYDVR0BBFYwVIAQ3UIfnF8G56sxHpZT4R7pP6EuMCwxKjAoBgNVBAMT
# IVBvd2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdIIQoQi1Z76XBaREzfaC
# AEywfDAJBgUrDgMCHQUAA4GBAIS/7pcaQ1Oxwtt0OAyNTAEcrR6qrcllzTwf0aQd
# DW/lfit6JYsr7cm5ajMguQBAWO83Sv0o2yV5U0Aj/PY+aFQPlxeC7FTdYtU2bWm3
# uob9HSrwnS09uQfmAIW9A0R+7KuyV3NFwKuYWfAz32EuwtLy6Uu7gsn56SKzfkWi
# 5MytMYIBYDCCAVwCAQEwQDAsMSowKAYDVQQDEyFQb3dlclNoZWxsIExvY2FsIENl
# cnRpZmljYXRlIFJvb3QCEH7Y5vpWg8C+SRFd4gabiW4wCQYFKw4DAhoFAKB4MBgG
# CisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcC
# AQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYE
# FAZLm+P+lcRyi8+5ZVCz6XLJfI+1MA0GCSqGSIb3DQEBAQUABIGAnWZCJYhZIfHe
# sjHckGPkvodEhf0BNvhKZZ2adSiMoe49UsIJMmvnV8g17V4TjJCU/zDwm1X32fr/
# iJ7r4f20hGvJpSEXpH5dBuFjNYPN/8k2VpvOYjOK+p5OhAVxpThKYBvpuQs+DN1C
# d8o+2zjYnLcLt5QB/LncE5jAEgsjdwI=
# SIG # End signature block
