#!/bin/sh

FEATURES="-funsigned-bitfields -funsigned-char -fvisibility=hidden -fPIC"
DEFINES="-DxxBIT=64 -DHAS_UNICODE=1 -DUNIX=1 -DWANT_REFCOUNTS=1 -D_DEBUG=1"
INCLUDES="-I./dwa"
FLAGS="-fast -fno-alias -shared -static-intel -Wall -Wno-unused-function"
FILES="dwa/dwa_fns.c"
CC=icc
LD_LIBRARY_PATH=/opt/intel/lib/intel64

echo "$CC $FEATURES $DEFINES $INCLUDES $FLAGS -o $1.so $FILES $1.c"
exec $CC $FEATURES $DEFINES $INCLUDES $FLAGS -o "$1.so" $FILES "$1.c"

