#!/bin/sh

DEFINES="-DxxBIT=64 -DHAS_UNICODE=1 -DUNIX=1 -DWANT_REFCOUNTS=1 -D_DEBUG=1"
INCLUDES="-I./dwa"
FLAGS="-O4 -shared -fPIC -acc -ta:tesla:nordc"
FILES="dwa/dwa_fns.c"
LOG=$1.log
CC=pgcc

echo "$CC $DEFINES $INCLUDES $FLAGS -o $1.so $FILES $1.c"
exec $CC $DEFINES $INCLUDES $FLAGS -o "$1.so" $FILES "$1.c" > $LOG 2>&1

